version: '3.8'

services:
  eureka:
    build: ./eureka-server
    image: merieem/eureka:1.0
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - app-network

  apigateway:
    build: ./apiGateway
    image: merieem/apigateway:1.0
    container_name: apiGateway
    ports:
      - "8058:8058"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
    depends_on:
      - eureka
      - user
      - db_user
      - keycloak
    networks:
      - app-network

  user:
    build: ./User
    image: merieem/user:1.0
    container_name: user
    ports:
      - "8023:8023"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_user:3306/user?createDatabaseIfNotExist=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
    depends_on:
      - eureka
      - db_user
    networks:
      - app-network

  db_user:
    image: mysql:5.7
    container_name: db_user
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=user
    volumes:
      - projet_db_user_data:/var/lib/mysql
      - ./init-mysql:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: keycloak
    ports:
      - "9098:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://db_user:3306/keycloak
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=root
    volumes:
      - projet_keycloak_data:/opt/keycloak/data
    command: ["start-dev"]
    depends_on:
      - db_user
    networks:
      - app-network
    restart: unless-stopped

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "MyCompany"
      LDAP_DOMAIN: "mycompany.com"
      LDAP_ADMIN_PASSWORD: admin
    ports:
      - "389:389"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    networks:
      - app-network
    restart: unless-stopped

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8090:80"
    depends_on:
      - openldap
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  projet_db_user_data:
  projet_keycloak_data:
  ldap_data:
  ldap_config:
